### ISSUE TITLE
Master branch is behind 1.1.0 tag

### ISSUE THREAD

**Issue by msound** [devinci-code/ahoy#27]
The 1.1.0 tag is basically the hash `d674c31`... I searched in your entire master branch commits, the HEAD is at `a7fcfb8e` and I cannot find the tag anywhere.

**Comment by frankcarey** [comment]
@msound yeah, seems like a commit snuck into the tag that was missing from master [d674c31ed7], but it looks like this is also in an outstanding PR https://github.com/devinci-code/ahoy/commit/f9b55fcc1e064e1d9c3242211cfb922c0555b9f5

**Comment by frankcarey** [comment]
I just merged 1.1.0 into master.
